baseURL = 'https://github.com/sofijacom/KL-blog/'
languageCode = 'en-us'
title = 'Sofiya Blog'
pagination.pagerSize = 5
theme = 'PaperMod'

[params]
  ShowFullTextinRSS = true
  comments = true
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = false
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  [params.assets]
    disableScrollBarStyle = true
    disableHLJS = true
  [params.homeInfoParams]
    title = "Hi there üëã" # "‚Ä¢Sofiya Blog‚Ä¢"
    content = "Expand your knowledge and stay up to date" # "Expand your knowledge and stay informed with our engaging blog posts"
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/sofijacom"
  [[params.socialIcons]]
    name = "twitter"
    url = "https://x.com/sofija_p2018"
  [[params.socialIcons]]
    name = "youtube"
    url = "https://www.youtube.com/@sofijacom"
  [[params.socialIcons]]
    name = "email"
    url = "mailto:sofija.p2018@gmail.com"
  [[params.socialIcons]]
    name = "rss"
    url = "https://sofijacom.github.io/KL-blog/index.xml"
    
[params.label]
text = "Sofiya Blog"
icon = "https://raw.githubusercontent.com/sofijacom/KL-blog/refs/heads/main/images/logo.jpg"
iconHeight = 35

[params.profileMode]
enabled = false   # Toggle default theme mode - true / false 
title = "Sofiya Blog"
subtitle = "Expand your knowledge and stay informed with our engaging blog posts"
imageUrl = "https://raw.githubusercontent.com/sofijacom/KL-blog/refs/heads/main/images/logo.jpg"
imageWidth = 120
imageHeight = 120
imageTitle = "my image"

[[params.profileMode.buttons]]
name = "Posts"
url = "posts"

[[params.profileMode.buttons]]
name = "Tags"
url = "tags"

[menu]
  [[menu.main]]
    identifier = "archive"
    name = "Archive"
    url = "/archive/" 
  [[menu.main]]
    identifier = "rss"
    name = "RSS"
    url = "/index.xml"
  [[menu.main]]
    identifier = "search"
    name = "Search" # üîç
    url = "/search/"
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"  
    tags = [
    "responsive",
    "simple",
    "clean",
    "light",
    "dark",
    "blog",
    "minimalist",
    "highlight.js",
    "search"
]
  [[menu.main]]
    identifier = "wiki"
    name = "WiKi"
    url = "https://github.com/adityatelange/hugo-PaperMod/wiki/"
    
[outputs]
  home = ["HTML", "RSS", "JSON"]
  
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = "catppuccin-macchiato"
    tabWidth = 2
    wrapperClass = "highlight"
    
[caches]
  [caches.images]
    dir = ':cacheDir/images'
    
[params.cover]
hidden = true
hiddenInList = false
hiddenInSingle = false

[params.editPost]
URL = "https://github.com/sofijacom/KL-blog/blob/main/content"
Text = "Wijziging voorstellen"
appendFilePath = true

[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1000
threshold = 0.4
minMatchCharLength = 0
limit = 10
keys = ["title", "permalink", "summary", "content"]

#[params.analytics.google]
#SiteVerificationTag = "XYZabc"

#[params.analytics.bing]
#SiteVerificationTag = "XYZabc"

#[params.analytics.yandex]
#SiteVerificationTag = "XYZabc"

